############################################################################
#
#  Program:  OpenSees
#
#  Purpose:  A Top-level Makefile to create the libraries needed
#	     to use the OpenSees framework.
#
#  Written: jeremic@ucdavis.edu; zhyang@ucdavis.edu 
#  Created: 01/2001
#
#  Send bug reports, comments or suggestions to jeremic@ucdavis.edu
#
############################################################################

# %---------------------------------%
# |  SECTION 1: PROGRAM             |
# %---------------------------------%
#
# Specify the location and name of the OpenSees interpreter program
# that will be created (if this all works!)

OpenSees_PROGRAM = $(HOME)/bin/OpenSees

# %---------------------------------%
# |  SECTION 2: PATHS               |
# %---------------------------------%
#
# Note: if vendor supplied BLAS and LAPACK libraries or if you have
# any of the libraries already leave the directory location blank AND
# remove the directory from DIRS.

BASE		= /usr/local
HOME		= /home/jeremic
FE		= $(HOME)/oofep/OpenSees/SRC

BLASdir      = $(HOME)/oofep/OpenSees/OTHER/BLAS
CBLASdir     = $(HOME)/oofep/OpenSees/OTHER/CBLAS
LAPACKdir    = $(HOME)/oofep/OpenSees/OTHER/LAPACK
SUPERLUdir   = $(HOME)/oofep/OpenSees/OTHER/SuperLU
ARPACKdir    = $(HOME)/oofep/OpenSees/OTHER/ARPACK
UMFPACKdir   = $(HOME)/oofep/OpenSees/OTHER/UMFPACK
METISdir     = $(HOME)/oofep/OpenSees/OTHER/METIS
SRCdir       = $(HOME)/oofep/OpenSees/SRC


DIRS        = $(SUPERLUdir)\
              $(ARPACKdir) \
              $(UMFPACKdir) \
              $(METISdir) \
              $(SUPERLUdir) \
              $(ARPACKdir) \
              $(UMFPACKdir) \
              $(SRCdir)

# %-------------------------------------------------------%
# | SECTION 3: LIBRARIES                                  |
# |                                                       |
# | The following section defines the libraries that will |
# | be created and/or linked with when the libraries are  | 
# | being created or linked with.                         |
# %-------------------------------------------------------%
#
# Note: if vendor supplied BLAS and LAPACK libraries leave the
# libraries blank. You have to get your own copy of the tcl/tk 
# library!! 
#
# Note: For libraries that will be created (any in DIRS above)
# make sure the directory exsists where you want the library to go!
			      
FE_LIBRARY      = $(HOME)/lib/libOpenSees.a
NDARRAY_LIBRARY = $(HOME)/lib/libndarray.a 
MATMOD_LIBRARY  = $(HOME)/lib/libmatmod.a  
LAPACK_LIBRARY  = $(HOME)/lib/libLapack.a
BLAS_LIBRARY    = $(HOME)/lib/libBlas.a
SUPERLU_LIBRARY = $(HOME)/lib/libSuperLU.a
CBLAS_LIBRARY   = $(HOME)/lib/libCBlas.a
ARPACK_LIBRARY  = $(HOME)/lib/libArpack.a
UMFPACK_LIBRARY = $(HOME)/lib/libUmfpack.a
METIS_LIBRARY   = $(HOME)/lib/libMetis.a
TCL_LIBRARY     = /usr/lib/libtk8.0.so \
                  /usr/X11R6/lib/libX11.a \
                  /usr/lib/libtcl8.0.so


# WATCH OUT .. These libraries are removed when 'make wipe' is invoked.
# $(FE_LIBRARY) \
#WIPE_LIBS	= $(NDARRAY_LIBRARY)  $(MAT_MOD_LIBRARY)  $(FE_LIBRARY)
WIPE_LIBS	= $(FE_LIBRARY) \
		          $(SUPERLU_LIBRARY) \
		          $(ARPACK_LIBRARY) \
		          $(UMFPACK_LIBRARY) \
	           $(METIS_LIBRARY)	 \
	           $(NDARRAY_LIBRARY) \
            $(MATMOD_LIBRARY)

# %---------------------------------------------------------%
# | SECTION 4: COMPILERS                                    |
# |                                                         |
# | The following macros specify compilers, linker/loaders, |
# | the archiver, and their options.  You need to make sure |
# | these are correct for your system.                      |
# %---------------------------------------------------------%

# ################################################### 
# # Compilers
# ################################################### 
# # DEFAULT
# ################################################### 
# CC++	  = g++
# CC     = gcc
# FC	    = g77


# Boris Jeremic@ucdavis.edu
###################################################  Portland Group
# ########  PGI PGI  PGI PGI PGI PGI PGI PGI  PGI PGI PGI PGI      
# CC++            =  pgCC
# CC              =  pgcc
# FC              =  pgf77
# LINKER           = pgCC 
# 
# C++FLAGS        =  -g -D_UNIX -Minfo=all 
# CFLAGS          =  -g	 -Minfo=all 
# FFLAGS          =  -g
# LINKFLAGS       =  -g
# ####..
# ######..CCFLAGS = -c -O2 -Munroll -Mnoframe -tp p6 -Minfo=all -Minline -Mconcur -o $*.o  ##>0.350u 29.360s 0:29.73 99.9%    0+0k 0+0io 284pf+0w
# ######..CCFLAGS = -c -O2 -Munroll -Mnoframe -tp p6 -Minfo=all -Minline -o $*.o  ##>0.350u 29.360s 0:29.73 99.9%    0+0k 0+0io 284pf+0w
# ######..CCFLAGS = -c -Mprof=lines -o $*.o  ##
# ######..CCFLAGS = -c -g -o $*.o  ##>0.330u 38.820s 0:39.18 99.9%     0+0k 0+0io 283pf+0w
# ######..CCFLAGS = -c  -Mvect  -O2 -o $*.o  ##  1.930u 6.880s 0:08.83 99.7%     0+0k 0+0io 151pf+0w
# ##CCFLAGS = -c -g -Minfo=all -o $*.o  ## 
######..LINKFLAGS = -Mconcur 
##LINKFLAGS = -lm

# ################################  Kuck and Associates Inc.
# ######  KAI KAI  KAI KAI KAI KAI KAI KAI  KAI KAI KAI KAI      
# CC++ =  KCC
# CC =   KCC
# LINKER= KCC
# FC   =  g77
# #FC   =  pgf90
# LINKER= KCC 
# 
# C++FLAGS        =  -g -D_UNIX -Wall 
# CFLAGS          =  -g	 -Wall
# FFLAGS          =  -g
# # ####..
# ##..##..CCFLAGS = -c  --strict_warnings +K0 --cpfe_only --display_error_number  -o $*.o   
# ##..##..CCFLAGS = -c  --strict_warnings +K0 --display_error_number  -o $*.o    
# ##..##..CCFLAGS = -c  --strict_warnings  --inline_auto_space_time=1.0 -O --display_error_number -o $*.o # 60.680u 6.590s 1:12.85 92.3% 0+0k 0+0io 61184pf+0w
# ##..##..CCFLAGS = -c  +K3  --strict_warnings  -O --abstract_pointer --abstract_float  --display_error_number -o $*.o #  1.570u 7.090s 0:08.67 99.8%     0+0k 0+0io 292pf+0w
# ##..CCFLAGS = -c  +K2  --strict_warnings  -O --display_error_number -o $*.o 
# ##..##..CCFLAGS = -c   --strict_warnings --inline_auto_space_time=1.0 +K3 --display_error_number -o $*.o # 196.760u 6.930s 3:26.86 98.4% 0+0k 0+0io 61538pf+0w
# ##..##..CCFLAGS = -c   --strict_warnings --inline_auto_space_time=75.0 +K3 --display_error_number -o $*.o # 196.760u 6.930s 3:26.86 98.4% 0+0k 0+0io 61538pf+0w
# ##..
##..


########################################    GNU
CC++            =  g++
CC              =  gcc
FC            =  g77
LINKER          =  g++
																					 
#C++FLAGS        =  -O2 -D_UNIX
#CFLAGS          =  -O2
#FFLAGS          =  -O2
#LINKFLAGS       =  

C++FLAGS        =  -g -D_UNIX -Wall
CFLAGS          =  -g	 -Wall
FFLAGS          =  -g
LINKFLAGS       =  -g
#####..
##..CC++ = g++
##..CC   = gcc
##..FC	  = g77
##..LINKER= g++

########################################     EGCS
# ##..
# ##..CC++ = egcs
# ##..LINKER= egcs
#   
########################################    MPI CC

##CC++ = mpiCC
##CC   = mpicc
##LINKER= mpiCC

##..########################################     INSURE++  CODEWIZARD
##..CC++            =  insure
##..CC              =  gcc
##..FC              =  g77
##..LINKER           =  g++ 
##..
##..C++FLAGS        =  -g -Zvm -Zvm -Zvm -D_UNIX -Wall
##..CFLAGS          =  -g	 -Wall
##..FFLAGS          =  -g
##..LINKFLAGS       =  -g
##..
##..CC++ = insure
##..CC   = gcc
##..LINKER= insure
##..#CC++ = codewizard
##..#CC   = gcc
##..#LINKER= codewizard
##..

########################################       I B M   AIX
##..# AIX C++   on IBM AIX
##..CC++ = xlC
##..CC   = xlc
##..LINKER= xlC


########################################     BORLAND
# DOS DOS DOS DOS DOS DOS DOS DOS DOS DOS DOS DOS DOS DOS DOS
##..CC = bcc
##..CCFLAGS = -c -w -rd -C -N -P -f87 -I\cmp\bc\include -L\cmp\bc\lib -i64 -mh -o $*.o
##..



AR		= ar 
ARFLAGS		= cqls
RANLIB		= ranlib

# Compiler Flags
#
# NOTES:
#    C++ FLAGS TAKE need _UNIX or _WIN32 for preprocessor directives
#         - the _WIN32 for the Windows95/98 or NT operating system.
#    C FLAGS used -DUSE_VENDOR_BLAS (needed in SuperLU) if UNIX in C++ FLAGS
#

# DEFINED ABOVE
# C++FLAGS        = -Wall -g -D_UNIX
# CFLAGS          = -Wall -g
# FFLAGS          = -Wall -g

#C++FLAGS        = -Wall -O2 -D_UNIX
#CFLAGS          = -Wall -O2
#FFLAGS          = -Wall -O


# DEFINED ABOVE
# # Linker
# #LINKER          = $(CC++)
# #LINKER          = g++
# LINKER          = pgCC
# LINKFLAGS       =  -g

# Misc
MAKE		          = make
CD              = cd
ECHO            = echo
RM              = rm
RMFLAGS         = -f
SHELL           = /bin/sh

# %---------------------------------------------------------%
# | SECTION 5: COMPILATION                                  |
# |                                                         |
# | The following macros specify the macros used in         |
# | to compile the source code into object code.            |
# %---------------------------------------------------------%

.SUFFIXES:
.SUFFIXES:	.C .c .f .f90 .cpp .o .cpp

#
# %------------------%
# | Default command. |
# %------------------%
#
.DEFAULT:
	@$(ECHO) "Unknown target $@, try:  make help"
#
# %-------------------------------------------%
# |  Command to build .o files from .f files. |
# %-------------------------------------------%
#

.cpp.o:
	@$(ECHO) Making $@ from $<
	$(CC++) $(C++FLAGS) $(INCLUDES) -c $< -o $@

.C.o:
	@$(ECHO) Making $@ from $<
	$(CC++) $(C++FLAGS) $(INCLUDES) -c $< -o $@
.c.o:
	@$(ECHO) Making $@ from $<
	$(CC) $(CFLAGS) -c $< -o $@
.f.o:      
	@$(ECHO) Making $@ from $<
	$(FC) $(FFLAGS) -c $< -o $@

# %---------------------------------------------------------%
# | SECTION 6: OTHER LIBRARIES                              |
# |                                                         |
# | The following macros specify other libraries that must  |
# | be linked with when creating executables. These are     |
# | platform specific and typically order does matter!!     |
# %---------------------------------------------------------%
MACHINE_LINKLIBS  = -L$(BASE)/lib \
                    -L$(HOME)/lib \



#MPI_LIB_DIR     = /usr/local/mpi/mpich/lib/ # BJ_UCD

MACHINE_NUMERICAL_LIBS  = -lm \
  $(ARPACK_LIBRARY) \
  $(SUPERLU_LIBRARY) \
  $(UMFPACK_LIBRARY) \
  $(LAPACK_LIBRARY)  \
  $(BLAS_LIBRARY) \
  $(CBLAS_LIBRARY) \
  -lg2c -ldl
#  $(MPI_LIB_DIR) \ # BJ_UCD



MACHINE_SPECIFIC_LIBS = 


# %---------------------------------------------------------%
# | SECTION 7: INCLUDE FILES                                |
# |                                                         |
# | The following macros specify include files needed for   |
# | compilation.                                            |
# %---------------------------------------------------------%
# BJ_UCD  MPI_INCLUDE_DIR = -I/usr/local/mpi/mpich/include


MACHINE_INCLUDES        = -I/usr/include      \
                     			  -I$(BASE)/include   \
              		          -I/usr/include/cxx  \
              		          -I$(HOME)/include   \
# BJ_UCD		  -I$(MPI_INCLUDE_DIR) 


# this file contains all the OpenSees/SRC includes
include $(FE)/Makefile.incl

TCL_INCLUDES = 

INCLUDES = $(TCL_INCLUDES) $(FE_INCLUDES) $(MACHINE_INCLUDES)








